package socket

import (
	"context"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/coder/websocket"

	"github.com/harshabose/mediapipe/pkg/https"
)

// Helper function to create a test server handler
func createTestServerHandler(t *testing.T, upgrader **Server) http.HandlerFunc {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if *upgrader == nil {
			t.Error("Server not initialized")
			return
		}

		if strings.Contains(r.URL.Path, "/ws/write/") {
			(*upgrader).WsWriteHandler(w, r)
		} else if strings.Contains(r.URL.Path, "/ws/read/") {
			(*upgrader).WsReadHandler(w, r)
		} else {
			http.NotFound(w, r)
		}
	})
}

// Helper function to create a test client config from a test server URL
func createTestClientConfig(testServerURL string) (ClientConfig, error) {
	testURL, err := url.Parse(testServerURL)
	if err != nil {
		return ClientConfig{}, err
	}

	port, err := strconv.ParseUint(testURL.Port(), 10, 16)
	if err != nil {
		return ClientConfig{}, err
	}

	return ClientConfig{
		Addr:           testURL.Hostname(),
		Port:           uint16(port),
		Path:           "/ws/write/testroom/testtopic", // Add proper WebSocket path
		MessageType:    websocket.MessageBinary,
		ReconnectDelay: 1 * time.Second,
		PingTimeout:    10 * time.Second,
		MaxRetry:       3,
		ReadTimeout:    time.Second,
		WriteTimeout:   time.Second,
		KeepConnecting: true,
	}, nil
}

// Helper function to wait for client connection
func waitForClientConnection(client *Client, timeout time.Duration) bool {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		metrics := client.GetMetrics()
		if state, ok := metrics["state"]; ok && state == "Connected" {
			return true
		}
		time.Sleep(100 * time.Millisecond)
	}
	return false
}

// TestClientServerConnection tests basic client-server connection establishment
func TestClientServerConnection(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	// Create a test server using httptest for better control
	var upgrader *Server
	testServer := httptest.NewServer(createTestServerHandler(t, &upgrader))
	defer testServer.Close()

	// Setup server
	serverConfig := DefaultServerConfig()
	serverConfig.SetDefaults()

	upgrader = NewServer(ctx, serverConfig, https.DefaultConfig())

	// Setup client
	clientConfig, err := createTestClientConfig(testServer.URL)
	if err != nil {
		t.Fatalf("Failed to create client config: %v", err)
	}

	client := NewClient(ctx, clientConfig)

	// Start connection (asynchronous)
	client.Connect()

	// Wait for connection to establish
	if !waitForClientConnection(client, 5*time.Second) {
		metrics := client.GetMetrics()
		t.Fatalf("Client failed to connect within timeout. Final state: %v", metrics["state"])
	}

	// Verify client state
	metrics := client.GetMetrics()
	if state, ok := metrics["state"]; !ok || state != "Connected" {
		t.Errorf("Expected client state to be 'Connected', got: %v", state)
	}

	// Clean up
	client.Close()
}

// TestClientServerDataExchange tests data exchange between client and server
func TestClientServerDataExchange(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	// Create a test server using httptest for better control
	var upgrader *Server
	testServer := httptest.NewServer(createTestServerHandler(t, &upgrader))
	defer testServer.Close()

	// Setup server
	serverConfig := DefaultServerConfig()
	serverConfig.SetDefaults()

	httpsConfig := https.Config{}
	upgrader = NewServer(ctx, serverConfig, httpsConfig)

	// Setup client
	clientConfig, err := createTestClientConfig(testServer.URL)
	if err != nil {
		t.Fatalf("Failed to create client config: %v", err)
	}

	client := NewClient(ctx, clientConfig)

	// Connect client
	client.Connect()

	// Wait for connection
	if !waitForClientConnection(client, 5*time.Second) {
		t.Fatalf("Failed to connect client to server")
	}

	// Test data generation and consumption
	testData := []byte("Hello, WebSocket!")

	// Generate data from client
	generatedData, err := client.Generate()
	if err != nil {
		t.Errorf("Failed to generate data: %v", err)
	}

	if len(generatedData) == 0 {
		t.Log("No data generated by client (this might be expected behavior)")
	}

	// Test consuming data
	err = client.Consume(testData)
	if err != nil {
		t.Errorf("Failed to consume data: %v", err)
	}

	// Verify metrics were updated
	metrics := client.GetMetrics()
	if packetsRead, ok := metrics["packets_read"]; ok {
		if packetsRead.(uint64) == 0 {
			t.Log("No packets read recorded (might be expected for this test)")
		}
	}

	// Clean up
	client.Close()
}

// TestMultipleClientsConnection tests multiple clients connecting to the same server
func TestMultipleClientsConnection(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	// Create a test server
	var upgrader *Server
	testServer := httptest.NewServer(createTestServerHandler(t, &upgrader))
	defer testServer.Close()

	// Setup server
	serverConfig := DefaultServerConfig()
	serverConfig.SetDefaults()

	httpsConfig := https.Config{}
	upgrader = NewServer(ctx, serverConfig, httpsConfig)

	// Create multiple clients
	numClients := 3
	clients := make([]*Client, numClients)
	var wg sync.WaitGroup

	for i := 0; i < numClients; i++ {
		clientConfig, err := createTestClientConfig(testServer.URL)
		if err != nil {
			t.Fatalf("Failed to create client config %d: %v", i, err)
		}

		clients[i] = NewClient(ctx, clientConfig)

		wg.Add(1)
		go func(clientIndex int) {
			defer wg.Done()

			clients[clientIndex].Connect()

			// Wait for connection
			if !waitForClientConnection(clients[clientIndex], 5*time.Second) {
				t.Errorf("Client %d failed to connect", clientIndex)
				return
			}

			// Verify connection
			metrics := clients[clientIndex].GetMetrics()
			if state, ok := metrics["state"]; !ok || state != "Connected" {
				t.Errorf("Client %d expected state 'Connected', got: %v", clientIndex, state)
			}
		}(i)
	}

	// Wait for all clients to connect
	wg.Wait()

	// Clean up all clients
	for _, client := range clients {
		if client != nil {
			client.Close()
		}
	}
}

// TestClientServerMetrics tests that both client and server properly track metrics
func TestClientServerMetrics(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	// Create test server
	var upgrader *Server
	testServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if upgrader == nil {
			t.Error("Server not initialized")
			return
		}

		if strings.Contains(r.URL.Path, "/ws/write/") {
			upgrader.WsWriteHandler(w, r)
		} else if strings.Contains(r.URL.Path, "/ws/read/") {
			upgrader.WsReadHandler(w, r)
		} else if strings.Contains(r.URL.Path, "/metrics") {
			upgrader.metricsHandler(w, r)
		} else {
			http.NotFound(w, r)
		}
	}))
	defer testServer.Close()

	// Setup server
	serverConfig := DefaultServerConfig()
	serverConfig.SetDefaults()

	httpsConfig := https.Config{}
	upgrader = NewServer(ctx, serverConfig, httpsConfig)

	// Setup client
	clientConfig, err := createTestClientConfig(testServer.URL)
	if err != nil {
		t.Fatalf("Failed to create client config: %v", err)
	}

	client := NewClient(ctx, clientConfig)

	// Connect client
	client.Connect()

	// Wait for connection
	if !waitForClientConnection(client, 5*time.Second) {
		t.Fatalf("Failed to connect client")
	}

	// Test client metrics
	clientMetrics := client.GetMetrics()
	expectedClientFields := []string{"state", "packets_written", "packets_read", "bytes_written", "bytes_read"}

	for _, field := range expectedClientFields {
		if _, exists := clientMetrics[field]; !exists {
			t.Errorf("Client metrics missing field: %s", field)
		}
	}

	// Test server metrics endpoint
	resp, err := http.Get(testServer.URL + "/metrics")
	if err != nil {
		t.Errorf("Failed to get server metrics: %v", err)
	} else {
		defer resp.Body.Close()
		if resp.StatusCode != http.StatusOK {
			t.Errorf("Expected status 200 for metrics endpoint, got: %d", resp.StatusCode)
		}
	}

	// Clean up
	client.Close()
}

// TestConnectionErrorHandling tests error handling in client-server communication
func TestConnectionErrorHandling(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	// Test connection to non-existent server
	clientConfig := ClientConfig{
		Addr:           "localhost",
		Port:           65432, // Non-existent port
		MessageType:    websocket.MessageBinary,
		ReconnectDelay: 500 * time.Millisecond,
		PingTimeout:    5 * time.Second,
		MaxRetry:       2, // Limit retries for faster test
		ReadTimeout:    1024,
		WriteTimeout:   1024,
		KeepConnecting: true,
	}

	client := NewClient(ctx, clientConfig)

	// Start connection attempt
	client.Connect()

	// Wait a bit and check that connection failed
	time.Sleep(2 * time.Second)

	// Verify client state reflects the failure
	metrics := client.GetMetrics()
	if state, ok := metrics["state"]; ok {
		if state == "Connected" {
			t.Error("Client should not be in Connected state after failed connection")
		}
		// State should be "Error" or "Connecting" or "Disconnected"
		if state != "Error" && state != "Connecting" && state != "Disconnected" {
			t.Logf("Client state after failed connection: %v", state)
		}
	}

	// Clean up
	client.Close()
}

// TestClientReconnection tests client reconnection functionality
func TestClientReconnection(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	// Create a test server that we can stop and restart
	var upgrader *Server
	var testServer *httptest.Server

	startServer := func() {
		testServer = httptest.NewServer(createTestServerHandler(t, &upgrader))

		serverConfig := DefaultServerConfig()
		serverConfig.SetDefaults()

		httpsConfig := https.Config{}
		upgrader = NewServer(ctx, serverConfig, httpsConfig)
	}

	// Start initial server
	startServer()
	originalURL := testServer.URL

	// Setup client with short reconnect interval for faster testing
	clientConfig, err := createTestClientConfig(originalURL)
	if err != nil {
		t.Fatalf("Failed to create client config: %v", err)
	}
	clientConfig.ReconnectDelay = 500 * time.Millisecond
	clientConfig.MaxRetry = 5

	client := NewClient(ctx, clientConfig)

	// Initial connection
	client.Connect()

	// Wait for initial connection
	if !waitForClientConnection(client, 5*time.Second) {
		t.Fatalf("Failed to connect client initially")
	}

	// Verify initial connection
	metrics := client.GetMetrics()
	if state, ok := metrics["state"]; !ok || state != "Connected" {
		t.Errorf("Expected initial state 'Connected', got: %v", state)
	}

	// Stop server to simulate connection loss
	testServer.Close()

	// Wait a bit for client to detect disconnection
	time.Sleep(1 * time.Second)

	// Check that client detected disconnection
	metrics = client.GetMetrics()
	state := metrics["state"]
	if state == "Connected" {
		t.Log("Client still shows as connected, this might be expected during reconnection attempts")
	}

	// Note: Actual reconnection testing would require more sophisticated 
	// URL handling since the test server gets a new port when restarted
	// For now, we just verify that the client attempts reconnection

	// Clean up
	client.Close()
}
